sudo: required

services: docker

before_install:
  - docker login -u xiuchang -p bd315c90-68c0-46f4-ac7c-1fe1d2d07219
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test